version: '3.1'

services:
  #mongo database
  mongo_db:
    container_name: mongo-users
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - users-net
  #database admin interface
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo_db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo-users:27017/
    networks:
      - users-net
  #users ms
  ms-users:
    build:
      context: ./
      args:
        - JAR_FILE=*.jar
    container_name: ms-users
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - mongo_db
    ports:
      - 8090:8090
    networks:
      - users-net
networks:
  users-net:
    name: proxy_network